const PRIMARY_COLOR = "#66bb6a";
const PRIMARY_LIGHT_COLOR = "#98ee99";
const PRIMARY_DARK_COLOR = "#338a3e";
const SECONDARY_COLOR = "#338a3e";
const SECONDARY_LIGHT_COLOR = "";
const BACKGROUD_COLOR = "#E8F5E9";

export {
  PRIMARY_COLOR,
  SECONDARY_COLOR,
  PRIMARY_LIGHT_COLOR,
  SECONDARY_LIGHT_COLOR,
  BACKGROUD_COLOR,
  PRIMARY_DARK_COLOR,
};
