const PRIMARY_COLOR = "#66bb6a";
const PRIMARY_LIGHT_COLOR = "#98ee99";
const SECONDARY_COLOR = "";
const SECONDARY_LIGHT_COLOR = "";

export {
    PRIMARY_COLOR,
    SECONDARY_COLOR,
    PRIMARY_LIGHT_COLOR,
    SECONDARY_LIGHT_COLOR
}
