name: Nodes



on: 
  push:
    branches: [release]
  workflow_dispatch:
       

jobs:
  build_test: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup nodejs 
        uses: actions/setup-node@v1
        with: 
          node-version: '16.x'
      - name: Install dependencies
        run: yarn
      - name: Check smell code
        run: yarn run lint
      - name: Build 
        run: yarn run build 
      - name: Test
        run: yarn run test 
  push_to_Dockerhub:
    runs-on: ubuntu-latest
    needs: [build_test]
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: dpcuong2/student-loan-web-client:latest
  deploy_to_vps:
    runs-on: ubuntu-latest
    needs: [push_to_Dockerhub]
    steps:
      - name: ssh to vps and deploy docker-compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.SSH_USER}}
          key: ${{secrets.SSH_PRIVATE_KEY}} 
          script_stop: true
          script: ./deploy.sh

